 package com.project.utils;

 import java.util.HashMap;
import java.util.Map;

 public class WeChatErrorCode
 {
   public static final Map<Integer,String> ERRORCODE = new HashMap<Integer,String>();

   static {
     ERRORCODE.put(Integer.valueOf(-1), "系统繁忙");
     ERRORCODE.put(Integer.valueOf(0), "请求成功");
     ERRORCODE.put(Integer.valueOf(40001), "获取access_token时AppSecret错误，或者access_token无效");
     ERRORCODE.put(Integer.valueOf(40002), "不合法的凭证类型");
     ERRORCODE.put(Integer.valueOf(40003), "服务号：不合法的OpenID；企业号：不合法的UserID");
     ERRORCODE.put(Integer.valueOf(40004), "不合法的媒体文件类型");
     ERRORCODE.put(Integer.valueOf(40005), "不合法的文件类型");
     ERRORCODE.put(Integer.valueOf(40006), "不合法的文件大小");
     ERRORCODE.put(Integer.valueOf(40007), "不合法的媒体文件id");
     ERRORCODE.put(Integer.valueOf(40008), "不合法的消息类型");
     ERRORCODE.put(Integer.valueOf(40009), "不合法的图片文件大小");
     ERRORCODE.put(Integer.valueOf(40010), "不合法的语音文件大小");
     ERRORCODE.put(Integer.valueOf(40011), "不合法的视频文件大小");
     ERRORCODE.put(Integer.valueOf(40012), "不合法的缩略图文件大小");
     ERRORCODE.put(Integer.valueOf(40013), "服务号：不合法的APPID；企业号：不合法的corpid");
     ERRORCODE.put(Integer.valueOf(40014), "不合法的access_token");
     ERRORCODE.put(Integer.valueOf(40015), "不合法的菜单类型");
     ERRORCODE.put(Integer.valueOf(40016), "不合法的按钮个数");
     ERRORCODE.put(Integer.valueOf(40017), "不合法的按钮类型");
     ERRORCODE.put(Integer.valueOf(40018), "不合法的按钮名字长度");
     ERRORCODE.put(Integer.valueOf(40019), "不合法的按钮KEY长度");
     ERRORCODE.put(Integer.valueOf(40020), "不合法的按钮URL长度");
     ERRORCODE.put(Integer.valueOf(40021), "不合法的菜单版本号");
     ERRORCODE.put(Integer.valueOf(40022), "不合法的子菜单级数");
     ERRORCODE.put(Integer.valueOf(40023), "不合法的子菜单按钮个数");
     ERRORCODE.put(Integer.valueOf(40024), "不合法的子菜单按钮类型");
     ERRORCODE.put(Integer.valueOf(40025), "不合法的子菜单按钮名字长度");
     ERRORCODE.put(Integer.valueOf(40026), "不合法的子菜单按钮KEY长度");
     ERRORCODE.put(Integer.valueOf(40027), "不合法的子菜单按钮URL长度");
     ERRORCODE.put(Integer.valueOf(40028), "不合法的自定义菜单使用用户");
     ERRORCODE.put(Integer.valueOf(40029), "不合法的oauth_code");
     ERRORCODE.put(Integer.valueOf(40030), "不合法的refresh_token");
     ERRORCODE.put(Integer.valueOf(40031), "服务号：不合法的openid列表；企业号：不合法的UserID列表");
     ERRORCODE.put(Integer.valueOf(40032), "服务号：不合法的openid列表长度；企业号：不合法的UserID列表长度");
     ERRORCODE.put(Integer.valueOf(40033), "不合法的请求字符，不能包含\\uxxxx格式的字符");
     ERRORCODE.put(Integer.valueOf(40035), "不合法的参数");
     ERRORCODE.put(Integer.valueOf(40038), "不合法的请求格式");
     ERRORCODE.put(Integer.valueOf(40039), "不合法的URL长度");
     ERRORCODE.put(Integer.valueOf(40040), "不合法的插件token");
     ERRORCODE.put(Integer.valueOf(40041), "不合法的插件id");
     ERRORCODE.put(Integer.valueOf(40042), "不合法的插件会话");
     ERRORCODE.put(Integer.valueOf(40048), "url中包含不合法domain");
     ERRORCODE.put(Integer.valueOf(40050), "不合法的分组id");
     ERRORCODE.put(Integer.valueOf(40051), "分组名字不合法");
     ERRORCODE.put(Integer.valueOf(40054), "不合法的子菜单url域名");
     ERRORCODE.put(Integer.valueOf(40055), "不合法的按钮url域名");
     ERRORCODE.put(Integer.valueOf(40056), "不合法的agentid");
     ERRORCODE.put(Integer.valueOf(40057), "不合法的callbackurl");
     ERRORCODE.put(Integer.valueOf(40058), "不合法的红包参数");
     ERRORCODE.put(Integer.valueOf(40059), "不合法的上报地理位置标志位");
     ERRORCODE.put(Integer.valueOf(40060), "设置上报地理位置标志位时没有设置callbackurl");
     ERRORCODE.put(Integer.valueOf(40061), "设置应用头像失败");
     ERRORCODE.put(Integer.valueOf(40062), "不合法的应用模式");
     ERRORCODE.put(Integer.valueOf(40063), "红包参数为空");
     ERRORCODE.put(Integer.valueOf(40064), "管理组名字已存在");
     ERRORCODE.put(Integer.valueOf(40065), "不合法的管理组名字长度");
     ERRORCODE.put(Integer.valueOf(40066), "不合法的部门列表");
     ERRORCODE.put(Integer.valueOf(40067), "标题长度不合法");
     ERRORCODE.put(Integer.valueOf(40068), "不合法的标签ID");
     ERRORCODE.put(Integer.valueOf(40069), "不合法的标签ID列表");
     ERRORCODE.put(Integer.valueOf(40070), "列表中所有标签（用户）ID都不合法");
     ERRORCODE.put(Integer.valueOf(40071), "不合法的标签名字，标签名字已经存在");
     ERRORCODE.put(Integer.valueOf(40072), "不合法的标签名字长度");
     ERRORCODE.put(Integer.valueOf(40073), "不合法的openid");
     ERRORCODE.put(Integer.valueOf(40074), "news消息不支持指定为高保密消息");
     ERRORCODE.put(Integer.valueOf(40077), "不合法的预授权码 ");
     ERRORCODE.put(Integer.valueOf(40078), "不合法的临时授权码 ");
     ERRORCODE.put(Integer.valueOf(40079), "不合法的授权信息 ");
     ERRORCODE.put(Integer.valueOf(40080), "不合法的suitesecret ");
     ERRORCODE.put(Integer.valueOf(40082), "不合法的suitetoken ");
     ERRORCODE.put(Integer.valueOf(40083), "不合法的suiteid ");
     ERRORCODE.put(Integer.valueOf(40084), "不合法的永久授权码 ");
     ERRORCODE.put(Integer.valueOf(40085), "不合法的suiteticket ");
     ERRORCODE.put(Integer.valueOf(40086), "不合法的第三方应用appid ");
     ERRORCODE.put(Integer.valueOf(41001), "缺少access_token参数");
     ERRORCODE.put(Integer.valueOf(41002), "服务号：缺少appid参数；企业号：缺少corpid参数");
     ERRORCODE.put(Integer.valueOf(41003), "缺少refresh_token参数");
     ERRORCODE.put(Integer.valueOf(41004), "缺少secret参数");
     ERRORCODE.put(Integer.valueOf(41005), "缺少多媒体文件数据");
     ERRORCODE.put(Integer.valueOf(41006), "缺少media_id参数");
     ERRORCODE.put(Integer.valueOf(41007), "缺少子菜单数据");
     ERRORCODE.put(Integer.valueOf(41008), "缺少oauth code");
     ERRORCODE.put(Integer.valueOf(41009), "服务号：缺少openid；企业号：缺少UserID");
     ERRORCODE.put(Integer.valueOf(41010), "缺少url");
     ERRORCODE.put(Integer.valueOf(41011), "缺少agentid");
     ERRORCODE.put(Integer.valueOf(41012), "缺少应用头像mediaid");
     ERRORCODE.put(Integer.valueOf(41013), "缺少应用名字");
     ERRORCODE.put(Integer.valueOf(41014), "缺少应用描述");
     ERRORCODE.put(Integer.valueOf(41015), "缺少Content");
     ERRORCODE.put(Integer.valueOf(41016), "缺少标题");
     ERRORCODE.put(Integer.valueOf(41017), "缺少标签ID");
     ERRORCODE.put(Integer.valueOf(41018), "缺少标签名字");
     ERRORCODE.put(Integer.valueOf(41021), "缺少suiteid");
     ERRORCODE.put(Integer.valueOf(41022), "缺少suitetoken");
     ERRORCODE.put(Integer.valueOf(41023), "缺少suiteticket");
     ERRORCODE.put(Integer.valueOf(41024), "缺少suitesecret");
     ERRORCODE.put(Integer.valueOf(41025), "缺少永久授权码");
     ERRORCODE.put(Integer.valueOf(42001), "access_token超时");
     ERRORCODE.put(Integer.valueOf(42002), "refresh_token超时");
     ERRORCODE.put(Integer.valueOf(42003), "oauth_code超时");
     ERRORCODE.put(Integer.valueOf(42004), "插件token超时");
     ERRORCODE.put(Integer.valueOf(42007), "预授权码失效");
     ERRORCODE.put(Integer.valueOf(42008), "临时授权码失效");
     ERRORCODE.put(Integer.valueOf(42009), "suitetoken失效");
     ERRORCODE.put(Integer.valueOf(43001), "需要GET请求");
     ERRORCODE.put(Integer.valueOf(43002), "需要POST请求");
     ERRORCODE.put(Integer.valueOf(43003), "需要HTTPS请求");
     ERRORCODE.put(Integer.valueOf(43004), "需要接收者关注");
     ERRORCODE.put(Integer.valueOf(43005), "需要好友关系");
     ERRORCODE.put(Integer.valueOf(43006), "需要订阅");
     ERRORCODE.put(Integer.valueOf(43007), "需要授权");
     ERRORCODE.put(Integer.valueOf(43008), "需要支付授权");
     ERRORCODE.put(Integer.valueOf(43009), "需要员工已关注");
     ERRORCODE.put(Integer.valueOf(430010), "需要处于回调模式");
     ERRORCODE.put(Integer.valueOf(430011), "需要企业授权");
     ERRORCODE.put(Integer.valueOf(44001), "多媒体文件为空");
     ERRORCODE.put(Integer.valueOf(44002), "POST的数据包为空");
     ERRORCODE.put(Integer.valueOf(44003), "图文消息内容为空");
     ERRORCODE.put(Integer.valueOf(44004), "文本消息内容为空");
     ERRORCODE.put(Integer.valueOf(45001), "多媒体文件大小超过限制");
     ERRORCODE.put(Integer.valueOf(45002), "消息内容超过限制");
     ERRORCODE.put(Integer.valueOf(45003), "标题字段超过限制");
     ERRORCODE.put(Integer.valueOf(45004), "描述字段超过限制");
     ERRORCODE.put(Integer.valueOf(45005), "链接字段超过限制");
     ERRORCODE.put(Integer.valueOf(45006), "图片链接字段超过限制");
     ERRORCODE.put(Integer.valueOf(45007), "语音播放时间超过限制");
     ERRORCODE.put(Integer.valueOf(45008), "图文消息超过限制");
     ERRORCODE.put(Integer.valueOf(45009), "接口调用超过限制");
     ERRORCODE.put(Integer.valueOf(45010), "创建菜单个数超过限制");
     ERRORCODE.put(Integer.valueOf(45015), "回复时间超过限制");
     ERRORCODE.put(Integer.valueOf(45016), "系统分组，不允许修改");
     ERRORCODE.put(Integer.valueOf(45017), "分组名字过长");
     ERRORCODE.put(Integer.valueOf(45018), "分组数量超过上限");
     ERRORCODE.put(Integer.valueOf(45024), "账号数量超过上限");
     ERRORCODE.put(Integer.valueOf(46001), "不存在媒体数据");
     ERRORCODE.put(Integer.valueOf(46002), "不存在的菜单版本");
     ERRORCODE.put(Integer.valueOf(46003), "不存在的菜单数据");
     ERRORCODE.put(Integer.valueOf(46004), "不存在的用户");
     ERRORCODE.put(Integer.valueOf(47001), "解析JSON/XML内容错误");
     ERRORCODE.put(Integer.valueOf(48001), "api功能未授权");
     ERRORCODE.put(Integer.valueOf(48002), "Api禁用");
     ERRORCODE.put(Integer.valueOf(48003), "suitetoken无效");
     ERRORCODE.put(Integer.valueOf(48004), "授权关系无效");
     ERRORCODE.put(Integer.valueOf(50001), "服务号：用户未授权该api；企业号：redirect_uri未授权");
     ERRORCODE.put(Integer.valueOf(50002), "员工不在权限范围");
     ERRORCODE.put(Integer.valueOf(50003), "应用已停用");
     ERRORCODE.put(Integer.valueOf(50004), "员工状态不正确（未关注状态）");
     ERRORCODE.put(Integer.valueOf(50005), "企业已禁用");
     ERRORCODE.put(Integer.valueOf(60001), "部门长度不符合限制");
     ERRORCODE.put(Integer.valueOf(60002), "部门层级深度超过限制");
     ERRORCODE.put(Integer.valueOf(60003), "部门不存在");
     ERRORCODE.put(Integer.valueOf(60004), "父亲部门不存在");
     ERRORCODE.put(Integer.valueOf(60005), "不允许删除有成员的部门");
     ERRORCODE.put(Integer.valueOf(60006), "不允许删除有子部门的部门");
     ERRORCODE.put(Integer.valueOf(60007), "不允许删除根部门");
     ERRORCODE.put(Integer.valueOf(60008), "部门名称已存在");
     ERRORCODE.put(Integer.valueOf(60009), "部门名称含有非法字符");
     ERRORCODE.put(Integer.valueOf(60010), "部门存在循环关系");
     ERRORCODE.put(Integer.valueOf(60011), "管理员权限不足，（user/department/agent）无权限");
     ERRORCODE.put(Integer.valueOf(60012), "不允许删除默认应用");
     ERRORCODE.put(Integer.valueOf(60013), "不允许关闭应用");
     ERRORCODE.put(Integer.valueOf(60014), "不允许开启应用 ");
     ERRORCODE.put(Integer.valueOf(60015), "不允许修改默认应用可见范围");
     ERRORCODE.put(Integer.valueOf(60016), "不允许删除存在成员的标签");
     ERRORCODE.put(Integer.valueOf(60017), "不允许设置企业");
     ERRORCODE.put(Integer.valueOf(60019), "不允许设置应用地理位置上报开关");
     ERRORCODE.put(Integer.valueOf(60020), "访问ip不在白名单之中");
     ERRORCODE.put(Integer.valueOf(60102), "UserID已存在");
     ERRORCODE.put(Integer.valueOf(60103), "手机号码不合法");
     ERRORCODE.put(Integer.valueOf(60104), "手机号码已存在");
     ERRORCODE.put(Integer.valueOf(60105), "邮箱不合法");
     ERRORCODE.put(Integer.valueOf(60106), "邮箱已存在");
     ERRORCODE.put(Integer.valueOf(60107), "微信号不合法");
     ERRORCODE.put(Integer.valueOf(60108), "微信号已存在");
     ERRORCODE.put(Integer.valueOf(60109), "QQ号已存在");
     ERRORCODE.put(Integer.valueOf(60110), "部门个数超出限制");
     ERRORCODE.put(Integer.valueOf(60111), "UserID不存在");
     ERRORCODE.put(Integer.valueOf(60112), "成员姓名不合法");
     ERRORCODE.put(Integer.valueOf(60113), "身份认证信息（微信号/手机/邮箱）不能同时为空");
     ERRORCODE.put(Integer.valueOf(60114), "性别不合法");
     ERRORCODE.put(Integer.valueOf(60023), "应用已授权予第三方，不允许通过分级管理员修改菜单");
   }
 }
